### ISSUE TITLE
Using with glorp

### ISSUE THREAD

**Issue by StephanEggermont** [svenvc/P3#1]
Pharo 7 latest 32 bit, Ubuntu 16.04LTS, local postgres install

Following the glorp booklet, and adapting it to P3.

Metacello new
   baseline: 'P3';
   repository: 'github://svenvc/P3';
   load: 'glorp'.

PharoDatabaseAccessor DefaultDriver: P3DatabaseDriver.

(section 4.5)
login := Login new
   database: PostgreSQLPlatform new;
   username: 'un';
   password: 'pw';
   connectString: 'localhost:5432_stephan';
   encodingStrategy: #utf8;
   yourself.
session := GlorpBookDescriptorSystem sessionForLogin: login.
session login

gives a
Instance of P3Client did not understand #queryEncoding

**Comment by StephanEggermont** [comment]
Also, with what version of Glorp is this supposed to work?It loads configuration 49, instead of 60, and therefore the old release,not v2 that was done by esteban maringolo

**Comment by svenvc** [comment]
I (and Glorp's unit tests) always do 'session accessor login' not 'session login' which tries to access the encoding (which P3 currently does not implement).

If you do (in Pharo 7 alpha.build.167.sha.6bff78ce8ecb91e5a53838267e7a1e1451c3c34c):
````
Metacello new
baseline: 'P3';
repository: 'github://svenvc/P3';
load: 'glorp'.

GlorpDatabaseLoginResource defaultLogin: (Login new
    database: PostgreSQLPlatform new;
    username: 'sven';
    password: '';
    connectString: 'localhost:5432_sven';
    encodingStrategy: #utf8;
    yourself).
````
you should be able to run Glorp unit tests.

The following should work after running the tests:
````
login := Login new
    database: PostgreSQLPlatform new;
    username: 'sven';
    password: '';
    connectString: 'localhost:5432_sven';
    encodingStrategy: #utf8;
    yourself.
session := GlorpDemoDescriptorSystem sessionForLogin: login.
session accessor login.
session save: GlorpAirline example1.
session readManyOf: GlorpAirline.
session logout.
````

**Comment by svenvc** [comment]
From BaselineOfP3>>#baselineOf:
````
		spec configuration: 'Glorp' with: [
			spec 
				versionString: #stable;
				repository: 'http://www.smalltalkhub.com/mc/DBXTalk/Configurations/main' ].
````

which seems to load .49 indeed.

I can't make head or tails from the current mess of different Glorp repos and who maintains what and how and what is more recent.

It is already a miracle that it all works in Pharo 7 ;-)

**Comment by svenvc** [comment]
For now the following addition would solve your issue
````
P3Client>>#queryEncoding
	^ self converter encoder identifier
````
but I must admit that I do not know how this is used by Glorp further on.

**Comment by svenvc** [comment]
see commit a15a56b46e5d61b40da1c2eef2e98870c0f390be

**Comment by StephanEggermont** [comment]
AFAIK the normal procedure is to have the newest configuration in the DBXTalk/Glorp repo, and copy that to DBXTalk/Configurations and the Pharo metarepos. Depending should then preferably be done on the one in Configurations. 
The copying part is often forgotten...

**Comment by svenvc** [comment]
I tested with the latest ConfigurationOfGlorp-StephanEggermont.61 in Pharo 7 and that seems OK
