### ISSUE TITLE
Problems with setting the parameters of P3PreparedStatement

### ISSUE THREAD

**Issue by jvdsandt** [svenvc/P3#13]
Currently the P3PreparedStatement >> #bindString: method just sends asString to each parameter. This works for some objects like Strings, Integers and Booleans, but not for ByteArrays, ScaledDecimals and probably some others.

I think we need a more intelligent conversion strategy. I see two options:

1. Dispatch to a convertParameter method in P3Converter to make to conversion dependent on the parameter type.
2. Make use of an extension method to do the conversion with a default implementation in Object. The extension method can be something like:

```
writeAsP3TextParameterOn: aStream type: aParameterDescription 
	"default implementation"
	self printOn: aStream
```
And for ByteArray:
```
writeAsP3TextParameterOn: aStream type: aParameterDescription 
	aStream nextPutAll: '\x'; nextPutAll: self hex
```
I think the seconds option is the most flexible but this option does require adding some class extensions.

**Comment by svenvc** [comment]
Yes, we need something like this, I would also go for the second option.

But I would like to have something that can also be part of the way parameters are spliced in normal non-prepared SQL statements.

**Comment by svenvc** [comment]
OK, good, closing. Thx.
