### ISSUE TITLE
Prepared statements error when query is long and differs slightly at the end

### ISSUE THREAD

**Issue by petr-fischer** [svenvc/P3#20]
Hello, psql prepared statements are identified by "name" (https://www.postgresql.org/docs/current/view-pg-prepared-statements.html), but in P3 client, the whole query is used as name - but, psql prepared statement name is limited :( 

Imagine this two queries:
`select id, name, enabled from table1 where name = ''123'' and id = 1`
This query is prepared - OK.
Second query:
`select id, name, enabled from table1 where name = ''123'' and id = 2`
Bang! PostgreSQL error message: P3Error PostgreSQL prepared statement "select id, name, enabled from table1 where name = '123' and id = 2" already exists

How to solve this? Add second peramater to the P3Client prepare: or maybe better, use some sort of hashes as prepared statement names internally?

**Comment by petr-fischer** [comment]
You can add this test method to the P3PreparedStatementTest test class

```
testTwoDifferentLongStatements
	| statement1 statement2 |
	
	client execute: 'DROP TABLE IF EXISTS table1'.
	client execute: 'CREATE TABLE table1 (id INTEGER, name TEXT, enabled BOOLEAN)'.
	
	statement1 := client prepare: 'select id, name, enabled from table1 where name = ''123'' and id = 1'.
	statement2 := client prepare: 'select id, name, enabled from table1 where name = ''123'' and id = 2'.

	statement1 close.
	statement2 close.
```

**Comment by svenvc** [comment]
OK, I understand, but why would you define the same prepared statement twice, exactly the same ?

I am trying to keep things simple.

What are the known limitations on prepared statement names (apart from them being unique) ?

**Comment by petr-fischer** [comment]
They are example (a little stupid) statements with sample difference only for testing.
Imagine this:
```
select something, someting from OBJS where OID = ? and CLASS = ? and INT = ?
```
vs
```
select something, someting from OBJS where OID = ? and CLASS = ? and STRING = ?
```
This two statements differ in column at the end and is not possible to prepare them via P3 client.

**Comment by petr-fischer** [comment]
I don't know excatly what is the limitation of PostgreSQL prepared statement name lentgh, found this, for example:
https://www.postgresql-archive.org/Limitation-of-prepared-statement-name-td6035788.html

**Comment by svenvc** [comment]
OK, I understand now.

Yes, this is an issue that must be resolved, indeed maybe with a hash.

Thanks for reporting it.

**Comment by jvdsandt** [comment]
Hello,
I also ran into this problem. I have submitted a pull request that uses a hash of the query string to make the first 63 characters of the name unique.

**Comment by svenvc** [comment]
https://github.com/svenvc/P3/pull/21
