### ISSUE TITLE
custom P3 error classes

### ISSUE THREAD

**Issue by pavel-krivanek** [svenvc/P3#26]
The error handling in P3 uses general `error:` calls on many places when something fails. It should signal custom errors with own classes so it can be more easily tested, converted and translated.

**Comment by svenvc** [comment]
You are right, but PostgreSQL is an extremely large and complex program. P3's mission is to be lean and mean.

Mapping all errors to different classes would be a lot of work.

It was a design decision to use just one error and one notification class (but it contains the actual DB error info).

So far this worked fine for me. How/where do you need more ?

**Comment by pavel-krivanek** [comment]
I think that it should be ok to have one just one error class but to use some aspect describing the problem or fill always some specific key in notice info.

For example, current code uses `self error: 'Password required' ` which does not give us any reasonable option to inform user in selected application language about the cause of problem.

In our application we use calls like `pdmError: aSymbol text: aString attribute: anAttribute` (and shorter variants while the symbol needs to be always set). It signals a custom error instance and we can use the symbol as key for error translation using Gettext + provide next information from the rest of the arguments.

**Comment by svenvc** [comment]
See https://github.com/svenvc/P3/commit/bf41906205b575d5e3400d3314e8fc74f945b012 for a new approach

This is based on how PostgreSQL errors are structured. Using #isLocal and #code you should have keys to work with, I hope.

**Comment by pavel-krivanek** [comment]
Thanks! in the commit, there seems to be a forgotten halt

**Comment by svenvc** [comment]
Ah yes, that method should not be called anyway, but I will remove it

**Comment by svenvc** [comment]
Done
