### ISSUE TITLE
Unsupported frontend protocol 2.0: server supports 3.0 to 3.0

### ISSUE THREAD

**Issue by alesshosry** [svenvc/P3#38]
I downloaded this library on Pharo 10 to connect to PostgresQL 14. However, an error was thrown while connecting to it as per below screenshot:

<img width="1191" alt="Screenshot 2022-09-29 at 11 09 59 AM" src="https://user-images.githubusercontent.com/26387399/192991977-7a326477-fbc0-4039-9072-f79d6fbbec75.png">

**Comment by svenvc** [comment]
OK, I was a bit confused, but P3 (only) supports frontend/backend protocol 3.0 (PostgreSQL version 7.4 [2003] and later).

So I guess you are not using P3Client. You could try to use it directly.

```
    (P3Client new url: 'psql://user:password@localhost') in: [ :client |
        [ client isWorking ] ensure: [ client close ] ].
```

Or some variation of that.

**Comment by alesshosry** [comment]
@svenvc my bad !
I was confused by the projects. I wanted to post this on [PgMetadata](https://github.com/deem0n/PgMetadata/tree/development) project that is using P3Client to handle Pharo 10, and I posted it here by mistake.
I confirm that P3Client is working perfectly with Postgres 14.

Sorry for the inconvenience.

**Comment by svenvc** [comment]
No problem.
