### ISSUE TITLE
Bug with Pharo 7

### ISSUE THREAD

**Issue by olivierauverlot** [svenvc/P3#7]
I just tested P3 with Pharo 7 and I got the following error message : Instance of ZnCharacterReadStream did not understand #binary.

The error is fired in ZTimezone >> fromFile: file

**Comment by svenvc** [comment]
Yeah, you should get the latest version of ZTimestamp (possibly #bleedingEdge)

**Comment by olivierauverlot** [comment]
Hi Sven,

Thanks for you help.

I have tested with this code in my baseline but this not work :(

'''
spec
    baseline: 'P3' with: [ 
    spec
      loads: #( );
      repository: 'github://svenvc/P3:master' ].
'''

**Comment by svenvc** [comment]
Like I said, you need to do

    ConfigurationOfZTimestamp loadBleedingEdge.

But I will make a new #stable release of ZTimestamp later tonight

**Comment by olivierauverlot** [comment]
ok, this works. Thanks :)

**Comment by svenvc** [comment]
I've make a new stable release of ZTimestamp, it should now work out of the box
